#!/bin/sh
SERVER_IP=""
SSH_KEY="$HOME/aws.pem"
rsync -ravzup -e "ssh -i $SSH_KEY" --exclude "logs" --exclude "node_modules" ParseServer/ ubuntu@$SERVER_IP:/usr/src/apps/ParseServer/
ssh -i $SSH_KEY ubuntu@$SERVER_IP "pm2 restart ParseServer"