#!/bin/sh
SERVER_IP=""
rsync -ravzup -e "ssh -i ~/aws.pem" --exclude "logs" --exclude "node_modules" ParseServer/ ubuntu@$SERVER_IP:/usr/src/apps/ParseServer/
ssh -i ~/aws.pem ubuntu@$SERVER_IP "pm2 restart ParseServer"